version: '3.8'
services:
  mongodb:
    container_name: mongodb
    restart: always
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - '27017:27017' 
    volumes:
      - ./MongoDB/db:/data/db
      - ./MongoDB/import:/opt/mongo/import

  mongo-express:
    container_name: mongo-express
    restart: always
    image: mongo-express:latest
    links:
      - mongodb
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpassword
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    ports:
      - '7999:8081'
    volumes: 
      - ./MongoDB:/data/db 
    depends_on:
      - mongodb

  unitao-data-service01:
    image: unitao/dataservice:localbuild
    container_name: unitao-data-service01
    restart: always
    stdin_open: true
    tty: true
    volumes:
      -  ./DataService01:/opt/UniTAO/config
      -  ./logs:/opt/UniTAO/log
    ports:
      - "8001:80"
    depends_on:
      - mongodb
    command: "DataService -id DataService01 -config /opt/UniTAO/config/config.json -log /opt/UniTAO/log"

  unitao-data-service01-admin:
    image: unitao/dataservice:localbuild
    container_name: unitao-data-service01-admin
    restart: "on-failure"
    volumes:
      -  ./DataService01:/opt/UniTAO/config
      -  ./logs:/opt/UniTAO/log
    depends_on:
      - mongodb
    command: "initMongo.sh /opt/UniTAO/log"
  
  unitao-data-service02:
    image: unitao/dataservice:localbuild
    container_name: unitao-data-service02
    restart: always
    stdin_open: true
    tty: true
    volumes:
      -  ./DataService02:/opt/UniTAO/config
      -  ./logs:/opt/UniTAO/log
    ports:
      - "8002:80"
    depends_on:
      - mongodb
    command: "DataService -id DataService02 -config /opt/UniTAO/config/config.json -log /opt/UniTAO/log"

  unitao-data-service02-admin:
    image: unitao/dataservice:localbuild
    container_name: unitao-data-service02-admin
    restart: "on-failure"
    volumes:
      -  ./DataService02:/opt/UniTAO/config
      -  ./logs:/opt/UniTAO/log
    depends_on:
      - mongodb
    command: "initMongo.sh /opt/UniTAO/log"

  unitao-inv-service:
    image: unitao/inventoryservice:localbuild
    container_name: unitao-inv-service
    restart: always
    stdin_open: true
    tty: true
    depends_on:
      - "unitao-data-service01"
      - "unitao-data-service02"
    volumes:
      -  ./InventoryService/config:/opt/UniTAO/config
      -  ./InventoryService/data:/opt/UniTAO/data
      -  ./logs:/opt/UniTAO/log
    ports:
      - "8004:80"
    command: "InventoryService -config /opt/UniTAO/config/config.json"

  unitao-inv-service-admin:
    image: unitao/inventoryservice:localbuild
    container_name: unitao-inv-service-admin
    restart: "no"
    stdin_open: true
    tty: true
    depends_on:
      - "unitao-inv-service"
    volumes:
      -  ./InventoryService/config:/opt/UniTAO/config
      -  ./InventoryService/data:/opt/UniTAO/data
      -  ./logs:/opt/UniTAO/log
    command: "InventoryServiceAdmin sync -config /opt/UniTAO/config/config.json -log /opt/UniTAO/log"
